"""Constants."""
URL = "https://myelectricaldata.fr"
TIMEOUT = 30
CONSUMPTION = "consumption"
PRODUCTION = "production"
DAILY_PROD = "daily_production"
DAILY_CONSUM = "daily_consumption"
DETAIL_PROD = "production_load_curve"
DETAIL_CONSUM = "consumption_load_curve"
PRICES = "prices"
CUM_PRICE = "cum_price"
CUM_VALUE = "cum_value"
OFFPEAK = "offpeak"
STANDARD = "standard"
