"""Constants."""

ATTR_CUM_PRICE = "cum_price"
ATTR_CUM_VALUE = "cum_value"
ATTR_END = "end"
ATTR_INTERVALS = "intervals"
ATTR_OFFPEAK = "offpeak"
ATTR_PRICES = "prices"
ATTR_SERVICE = "service"
ATTR_STANDARD = "standard"
ATTR_START = "start"
CONSUMPTION = "consumption"
DAILY_CONSUM = "daily_consumption"
DAILY_PROD = "daily_production"
DETAIL_CONSUM = "consumption_load_curve"
DETAIL_PROD = "production_load_curve"
PRODUCTION = "production"
TIMEOUT = 30
URL = "https://myelectricaldata.fr"
