name: Upload Python Package

on:
  release:
    types: ["published"]

  push:
    tags:
      - "*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to PyPi
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: 🔢 Set version number
        run: |
          export version=${{ github.ref }}
          sed -i "s|replace_by_workflow|${version##*/}|" ./pyproject.toml
          cat ./pyproject.toml

      - name: Build package
        shell: bash
        run: |
          python -m build

      - name: 🚀 Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
